import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import CommentSection from "../components/CommentSection";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-xl text-white">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis, est, accusamus fugiat alias odio earum optio quaerat nisi debitis adipisci ipsum ab exercitationem fuga ratione vero voluptates laborum itaque totam!
          </h1>
          <div>
            <CommentSection />
          </div>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
